##### 异常的标准处理

```java
package com.covet.testproject;

import org.apache.log4j.Logger;

public class TestException {

	static Logger log = Logger.getLogger(TestException.class);

	
	/*
	 * 模拟用户调用
	 */
	public static void main(String[] args) {
		// 程序入口
		ReturnMessage returnMessage = new ReturnMessage();
		returnMessage = userController(1, 1);  // (1, 1); (11, 1);
		System.err.println(returnMessage);
	}

	
	/*
	 * 模拟Controllers
	 */
	private static ReturnMessage userController(int a, int b) {
		log.info(String.format("调用userController类userController方法开始.参数为a:%s,b:%s", a + "", b + ""));
		ReturnMessage returnMessage = new ReturnMessage();
		try {
			userService(a, b);
			returnMessage.setCode(ReturnMessage.SUCCESS_CODE);
			returnMessage.setMsg(ReturnMessage.SUCCESS_VAL);
			returnMessage.setObject(null);
		} catch (Exception e) {
			returnMessage.setCode(ReturnMessage.FAIL_CODE);
			returnMessage.setMsg(ReturnMessage.FAIL_VAL);
			returnMessage.setObject(null);
		}
		log.info("调用userController类userController方法结束....");
		return returnMessage;
	}

	
	/*
	 * 模拟Service
	 */
	// 添加事务 抛出异常时事务回滚
	private static void userService(int a, int b) throws CustomException, Exception {
		try {
			// 业务异常
			if (!(0 < a && a < 10)) { // 判断0 < a < 10 checked异常
				throw new CustomException("参数a必须在1-10之间"); // 业务异常 提示错误信息
			}
			userDao(a, b);
		} catch (ArithmeticException e) { // 已知算术异常 Runtime运行时异常
			log.error("算术异常"+e.getMessage()); // 打印日志
			e.printStackTrace(); // 答应堆栈信息
			throw new CustomException("算术异常" + e.getMessage()); // 异常转义,转成用户可以理解的错误信息
		}catch (CustomException e) { // 已知算术异常 Runtime运行时异常
			log.error("自定义异常"+e.getMessage()); // 打印日志
			e.printStackTrace(); // 答应堆栈信息
			throw new CustomException("自定义异常" + e.getMessage()); // 异常转义,转成用户可以理解的错误信息
		}  
		catch (Exception e) {
			log.error("未知异常"); // 打印日志
			e.printStackTrace(); // 答应堆栈信息
			throw new CustomException("未知异常"); // 异常转义
		}
		log.info("调用service方法结束,无异常"); // 遇到throw会将程序终止,所以不会执行到这里.没有异常才会执行到这里.
	}

	
	/*
	 * 模拟Dao
	 */
	private static void userDao(int a, int b) {
		int c = a / b; // 模拟DAO抛出异常
	}

	
	/*
	 * 模拟错误信息返回类
	 */
	static class ReturnMessage {
		private final static String SUCCESS_CODE = "200";
		private final static String FAIL_CODE = "400";
		private final static String SUCCESS_VAL = "success";
		private final static String FAIL_VAL = "fail";
		
		private String code;
		private String msg;
		private Object object;

		public ReturnMessage() {
			super();
		}

		public ReturnMessage(String code, String msg, Object object) {
			super();
			this.code = code;
			this.msg = msg;
			this.object = object;
		}

		public String getCode() {
			return code;
		}

		public void setCode(String code) {
			this.code = code;
		}

		public String getMsg() {
			return msg;
		}

		public void setMsg(String msg) {
			this.msg = msg;
		}

		public Object getObject() {
			return object;
		}

		public void setObject(Object object) {
			this.object = object;
		}

		@Override
		public String toString() {
			return "ReturnMessage [code=" + code + ", msg=" + msg + ", object=" + object + "]";
		}

	}

	
	/*
	 * 自定义异常类
	 */
	static class CustomException extends Exception {
		private static final long serialVersionUID = 7837615560834135396L;

		public CustomException() {
			super();
		}

		public CustomException(String msg) {
			super(msg);
		}
	}

}


```

